version: "3"

services:
  accounts:
    container_name: xarples-accounts
    build:
      context: .
      dockerfile: ./packages/xarples-accounts-api/development.Dockerfile
    ports:
      - 5000:5000
    environment:
      - NODE_ENV=development
    volumes: 
      - .:/usr/local/src/xarples
      - /usr/local/src/xarples/node_modules
      - /usr/local/src/xarples/src/accounts/node_modules